@startuml US1008_SD
autonumber

actor "Student" as S
participant "RequestEnrolmentUI" as UI <<presentation>>
participant "RequestEnrolmentController" as CTRL <<application>>
participant "AuthenticationService" as AUTH <<service>>
participant "ListCourseService" as SRV <<service>>
participant "Enrolment" as E <<domain>>
participant "CourseDTO" as DTO <<dto>>
participant "EnrolmentDTO" as EDTO <<dto>>

database CourseRepository as REP <<repository>>
database EnrolmentRepository as EREP <<repository>>
database StudentRepository as SREP <<repository>>

activate S

S -> UI : asks to list all the courses available for enrolment
activate UI

UI -> CTRL : new(courseRepository, enrolmentRepository, studentRepository, authenticationService)
activate CTRL
CTRL -> SRV : service=new(courseRepository)
deactivate CTRL

UI -> CTRL : listOpenForEnrolmentCourses()
activate CTRL
CTRL -> AUTH : loggedinUserWithPermissions()
activate AUTH
AUTH --> CTRL : authenticatedUser
deactivate AUTH
CTRL -> SREP : findByUsername(authenticatedUser.username())
activate SREP
SREP --> CTRL : student
deactivate SREP
CTRL -> EREP : findWithUserAndCourse()
activate EREP
EREP --> CTRL : enrolments
deactivate EREP
CTRL -> SRV : listOpenForEnrolment()
activate SRV
SRV -> REP : findAllOpenForEnrolment()
activate REP
REP --> SRV : courses
deactivate REP

loop for each course
  SRV -> SRV : isEnroled(student, course)
  opt if is not enroled
    SRV -> E : toDTO(course)
    activate E
    E -> DTO : new
    deactivate E
  end opt
end loop

SRV --> CTRL : courses
deactivate SRV
CTRL --> UI : courses
deactivate CTRL

UI --> S : lists all available courses
deactivate UI

S -> UI : selects the desired course
activate UI
UI -> UI : selectedCourse = select(courses, index)
UI --> S : asks to confirm action
deactivate UI

S -> UI : confirms the action
activate UI
UI -> CTRL : requestEnrolment(selectedCourse)
activate CTRL
CTRL -> AUTH : loggedinUserWithPermissions()
activate AUTH
AUTH --> CTRL : authenticatedUser
deactivate AUTH
CTRL -> SREP : findByUsername(authenticatedUser.username())
activate SREP
SREP --> CTRL : student
deactivate SREP
CTRL -> REP : ofIdentity(selectedCourse.code())
activate REP
REP --> CTRL : course
deactivate REP
CTRL -> E : enrolment=new(course, student)
CTRL -> EREP : save(enrolment)
activate EREP
EREP --> CTRL : enrolment
deactivate EREP
CTRL -> E : toDTO(enrolment)
activate E
E -> EDTO : new
E --> CTRL : enrolmentDTO
deactivate E
deactivate EREP
CTRL --> UI : enrolmentDTO
deactivate CTRL
UI--> S : reports the success of the enrolment request
deactivate UI

deactivate S

@enduml
