@startuml US3007_CD

interface BoardRepository {
  {abstract} findAllActiveBoardsWithUserWritePermission()
}

interface PostItRepository {
  {abstract} findLatestFromUserByBoardId(boardId, username)
  {abstract} findLatestVersionOfBoard(boardId)
  {abstract} save(postIt)
}

class ListBoardService {
  - boardRepository

  + ListBoardService(boardRepository)

  + userWritableBoards(username)
}

class ListPostItService {
  - postItRepository

  + ListPostItService(postItRepository)

  + userUpdatablePostIts(boardId, username)
}

class ImageEncoderService {
  + encodeImage(imagePath)
}

class BoardService {
  - boardRepository
  - postItRepository

  + BoardService(boardRepository)

  + isCellAvailable(boardId, x, y)
  + checkCellExists(boardId, x, y)
  + existsPostIt(latestPostIts, x, y)
}

class ChangePostItUI {}

class ChangePostItController {
  - boardRepository
  - postItRepository

  + ChangePostItController(boardRepository, postItRepository)

  + listUserWritableBoards()
  + listBoardPostItsCreatedByUser(boardId)
  + validateCoordinates(boardId, x, y)
  + updatePostIt(boardId, postItId, x, y, title, description, imagePath)
  + savePostIt(postIt)
}

class PostIt {
  - title
  - coordinates
  - user
  - board
  - state
  - createdAt
  - isLatest
  - description
  - image

  + update(title, x, y, description, encodedImage)
  + delete()
}

class PostItDTO {
  + toDto()
}

class BoardDTOParser {
  + toDto()
}

class Board {
}


class BoardDTO {
  + toDto()
}

class BoardDTOParser {
  + toDto()
}


ChangePostItUI ..> ChangePostItController
ChangePostItController --> ListBoardService
ChangePostItController --> BoardService
ChangePostItController --> ListPostItService
ChangePostItController --> ImageEncoderService

ListBoardService ..> Board
ListBoardService --> BoardRepository
BoardService --> PostItRepository
ListPostItService --> PostItRepository

BoardService ..> PostIt
ListPostItService ..> PostIt
BoardService ..> Board
BoardDTOParser ..> BoardDTO
BoardDTOParser ..> Board

PostItDTOParser ..> PostItDTO
PostItDTOParser ..> PostIt

@enduml
