@startuml US4002_CD

class CancelMeetingUI {

}

class CancelMeetingController {
- authorizationService
- meetingRepository
- inviteRepository
- meetingService

+ CancelMeetingController(authorizationService, meetingRepository,
inviteRepository)

+ listNotCanceledScheduledMeetings()
+ cancelMeeting(meeting)
- getAuthenticatedUser()
}


class Meeting {
- id
- duration
- scheduledBy
- canceledAt
- time

+ toDto()
+ cancel()
}

class MeetingDTO {
- id
- duration
- scheduledBy
- canceledAt
- time
}

class Invite {
- id
- status
- meeting
- user

+ status()
}

class InviteStatus {
- status

+ cancel()
}

enum Status {
PENDING
ACCEPTED
REJECTED
CANCELED
NO_AWNSER
}



class MeetingService {
- meetingRepository

+ MeetingService(meetingRepository)

+ notCanceledMeetingsScheduledBy(user)
}

interface MeetingRepository {
+ findNotCanceledMeetingsByOwner(user)
}

class InMemoryMeetingRepository {
+ findNotCanceledMeetingsByOwner(user)
}

class JpaMeetingRepository {
+ findNotCanceledMeetingsByOwner(user)
}

interface InviteRepository {
+ findByMeetingID(meetingID)
+ save(invite)
}

class InMemoryInviteRepository {
+ findByMeetingID(meetingID)
}

class JpaInviteRepository {
+ findByMeetingID(meetingID)
}

class RepositoryFactory {
  + RepositoryFactory()
}


class PersistenceContext {
  - repositories()
}


MeetingService ..> Meeting
MeetingService ..> MeetingDTO
MeetingService ..> MeetingRepository

MeetingRepository <|.. InMemoryMeetingRepository
MeetingRepository <|.. JpaMeetingRepository

InviteRepository <|.. InMemoryInviteRepository
InviteRepository <|.. JpaInviteRepository

CancelMeetingController --> MeetingService
CancelMeetingController ..> Invite

Invite --> InviteStatus
InviteStatus --> Status


CancelMeetingUI ..> PersistenceContext
PersistenceContext ..> RepositoryFactory
RepositoryFactory --> MeetingRepository
RepositoryFactory --> InviteRepository

CancelMeetingUI ..> CancelMeetingController

@enduml
