@startuml US2002_SSD
autonumber

actor "Student" as student
participant ":System" as system

student -> system: request to see future exams

system -> student: lists the courses the student's enrolled in

student -> system: selects the desired course

system -> student: lists all future exams of the chosen course

@enduml
