@startuml US3004_SSD
autonumber

actor "User" as U
participant "System" as SYS

activate U

U -> SYS : wants to share a board with someone else
activate SYS
SYS --> U : lists the boards the user is owner of
deactivate SYS

U -> SYS : selects a board
activate SYS
SYS --> U : asks to insert the email of the user to share the board with
deactivate SYS

U -> SYS : inserts the email of the user to share the board with
activate SYS
SYS --> U : asks the permission type to assign to the user
deactivate SYS

U -> SYS : selects the permission type to assign to the user
activate SYS
SYS --> U : informs the operation success
deactivate SYS

deactivate U

@enduml
