@startuml US1005_SSD
autonumber

actor "Manager" as manager
participant ":System" as system

activate manager

manager -> system : Asks to set the teachers of a course
system -> manager : Lists all available courses and asks to select one
manager -> system : Selects a course
system -> manager : Asks if he wants to set regular teachers\nor teacher in charge
manager -> system : Selects an option
system -> manager : Lists all available teachers and asks to select one
manager -> system : Selects a teacher
system -> manager : Informs operation success\nand asks if he wants to set another teacher
