@startuml US2006_SSD
autonumber

actor Teacher as "Teacher"
actor System as "System"

Teacher -> System: requests to see a list of exam grades of his/her courses
System -> Teacher: displays the courses that teacher's lectures
Teacher -> System: chooses the desired course
System -> Teacher: asks to choose between evaluation and formative exams
Teacher -> System: selects the desired format
System -> Teacher: displays all the exams of the chosen course and format
Teacher -> System: selects the desired exam
System -> Teacher: displays all course student's grades for the chosen exam

@enduml
