@startuml US1004_SSD
'https://plantuml.com/sequence-diagram
actor "Manager" as manager
participant ":System" as system
autonumber


manager -> system: requests to change course status

system -> manager: lists all the possible toggle operations

manager -> system: selects one

system -> manager: displays all the available courses for the chosen toggle operation

manager -> system: selects the desired course

system -> manager: asks to confirm the change of the course status

manager -> system: confirms operation

system -> manager: informs operation success

@enduml
