@startuml US3006_SD
autonumber

actor "User" as M
participant "CreatePostItUI" as UI <<presentation>>
participant "CreatePostItController" as CTRL <<application>>
participant "ListBoardService" as LBSRV <<service>>
participant "BoardService" as BSRV <<service>>
participant "ImageEncoderService" as IESRV <<service>>
participant "Board" as B <<domain>>
participant "PostIt" as P <<domain>>
participant "BoardDTO" as BDTO <<dto>>

database BoardRepository as BREP <<repository>>
database PostItRepository as PREP <<repository>>

activate M

M -> UI : asks to create a post-it
activate UI

UI -> CTRL : new(boardRepository, postItRepository, imageEncoderService)
activate CTRL
CTRL -> LBSRV : new(boardRepository)
activate LBSRV
deactivate LBSRV
UI -> CTRL : listBoardsThatUserCanWrite()

CTRL -> LBSRV : userWritableBoards(userId)
activate LBSRV
LBSRV -> BREP : findAllActiveWithUserWritePermission(userId)
activate BREP
BREP --> LBSRV : boards
deactivate BREP

loop for each board
  LBSRV -> B : toDTO(board)
  activate B
  B -> BDTO : new()
  activate BDTO
  deactivate BDTO
  deactivate B
end loop

LBSRV --> CTRL : boards
deactivate LBSRV
CTRL --> UI : boards
deactivate CTRL

UI --> M : asks to select the board
deactivate UI

M -> UI : selects the board
activate UI

UI --> M : asks to select the post-it coordinates
deactivate UI

M -> UI : selects the post-it coordinates
activate UI
UI -> CTRL : validateCoordinates(boardId, x, y)
activate CTRL
CTRL -> BSRV : new(boardRepository, postItRepository)
activate BSRV
deactivate BSRV

CTRL -> BSRV : isCellAvailable(boardId, x, y)
activate BSRV
BSRV -> BSRV : checkCellExists(boardId, x, y)
activate BSRV
deactivate BSRV
BSRV -> PREP : findLatestByBoardId(boardId)
activate PREP
PREP --> BSRV : postIts
deactivate PREP
BSRV -> BSRV : existsPostIt(postIts, x, y)
activate BSRV
deactivate BSRV

BSRV --> CTRL : true
deactivate BSRV
CTRL --> UI : true
deactivate CTRL

UI --> M :  asks to enter the title, description and image of the post-it
deactivate UI

M --> UI : enters the requested data
activate UI

UI -> CTRL : createPostIt(boardId, x, y, title, description, imagePath)
activate CTRL

CTRL -> IESRV : encodeImage(imagePath)

CTRL -> P : new(board, user, title, x, y, description, encodedImage)
activate P
deactivate P

CTRL -> P : containsOfIdentity()
activate P
deactivate P

CTRL -> CTRL : savePostIt(postIt)
activate CTRL
CTRL -> PREP : savePostIt()
activate PREP
deactivate PREP
deactivate CTRL


CTRL --> UI : success
deactivate CTRL

UI --> M : informs operation success
deactivate UI


deactivate M

@enduml
