@startuml US1003_CD

class RepositoryFactory {
  + RepositoryFactory()
}

interface CourseRepository {
  + save(course)
}

class InMemoryCourseRepository {
  + save(course)
}

class JpaCourseRepository {
  + save(course)
}

class PersistenceContext {
  - repositories()
}

class ManageCourseEnrolmentStateUI {}

class ManageCourseEnrolmentStateController {
  + listNotClosedCourses()
  + toggleEnrolmentState(course)
}

class Course {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt

  + toggleEnrolmentState()
}

enum CourseState {
  CLOSED
  OPEN
  IN_PROGRESS
  FINISHED
}

enum CourseEnrolmentState {
  OPEN
  CLOSED
}

ManageCourseEnrolmentStateUI ..> ManageCourseEnrolmentStateController
ManageCourseEnrolmentStateController ..> PersistenceContext
ManageCourseEnrolmentStateController ..> Course
PersistenceContext ..> RepositoryFactory
RepositoryFactory --> CourseRepository

CourseRepository <|.. InMemoryCourseRepository
CourseRepository <|.. JpaCourseRepository

Course --> CourseState
Course --> CourseEnrolmentState

@enduml
