@startuml US1003_STATE

[*] --> CLOSED : create

CLOSED --> OPEN : open
OPEN --> CLOSED : close
OPEN --> ENROLL : open enrollments
ENROLL -> OPEN : close enrollments
ENROLL --> IN_PROGRESS : start
OPEN --> IN_PROGRESS : start
IN_PROGRESS --> [*] : close

@enduml
