@startuml US1003_CD

class RepositoryFactory {
  + RepositoryFactory()
}

interface CourseRepository {
  {abstract} findAllNotClosed()
  {abstract} save(course)
}

class InMemoryCourseRepository {
  + findAllNotClosed()
  + save(course)
}

class JpaCourseRepository {
  + findAllNotClosed()
  + save(course)
}

class PersistenceContext {
  - repositories()
}

class CourseService {
  + CourseService(courseRepository)

  + listNotClosedCourses()
  + toggleEnrolmentState(course)
  + save(course)
}

class ManageCourseEnrolmentStateUI {}

class ManageCourseEnrolmentStateController {
  + listNotClosedCourses()
  + toggleEnrolmentState(course)
}

class Course {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt

  + toggleEnrolmentState()
}

class CourseMapper {
  + {static} toDto(course)
}

enum CourseState {
  CLOSED
  OPEN
  IN_PROGRESS
  FINISHED
}

enum CourseEnrolmentState {
  OPEN
  CLOSED
}

class CourseDTO {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt
}

ManageCourseEnrolmentStateUI ..> ManageCourseEnrolmentStateController
ManageCourseEnrolmentStateController ..> PersistenceContext
ManageCourseEnrolmentStateController --> CourseService
PersistenceContext ..> RepositoryFactory
RepositoryFactory --> CourseRepository

CourseService ..> Course
CourseService ..> CourseMapper
CourseService ..> CourseRepository

CourseMapper ..> Course
CourseMapper ..> CourseDTO

CourseRepository <|.. InMemoryCourseRepository
CourseRepository <|.. JpaCourseRepository

Course --> CourseState
Course --> CourseEnrolmentState

@enduml
