@startuml US1003_SD
autonumber

actor "Manager" as M
participant "ManageEnrolmentsUI" as UI <<presentation>>
participant "ManageEnrolmentController" as CTRL <<application>>
participant "CourseListService" as SRV <<service>>
participant "Course" as C <<domain>>
participant "CourseDTO" as DTO <<dto>>

database CourseRepository as REP <<repository>>

activate M

M -> UI : asks to list all the courses and their states
activate UI

UI -> CTRL : new(courseRepository)
activate CTRL
CTRL -> SRV : service=new(courseRepository)
deactivate CTRL

UI -> CTRL : listNotClosedCourses()
CTRL -> SRV : listNotClosedCourses()
activate CTRL
activate SRV
SRV -> REP : findAllNotClosed()
activate REP
REP --> SRV : courses
deactivate REP

loop for each course
  SRV -> C : toDTO(course)
  activate C
  C -> DTO : new
  deactivate C
end loop

SRV --> CTRL : courses
deactivate SRV
CTRL --> UI : courses
deactivate CTRL

UI --> M : lists all the non finished courses
deactivate UI

M -> UI : selects the desired course
activate UI
UI -> UI : selectedCourse = select(courses, index)
UI --> M : asks to confirm action
deactivate UI

M -> UI : confirms the action
activate UI
UI -> CTRL : toggleEnrolmentState(selectedCourse)
activate CTRL
CTRL -> C : course=toggleEnrolmentState()
activate C
deactivate C
CTRL -> REP : save(course)
activate REP
REP --> CTRL : newCourse
deactivate REP
CTRL --> UI : newCourse
deactivate CTRL
UI--> M : reports the success of the toggle operation
deactivate UI

deactivate M

@enduml
