@startuml US1003_SD
autonumber

actor "Manager" as M
participant "ManageEnrolmentsUI" as UI <<presentation>>
participant "ManageEnrolmentController" as CTRL <<application>>
participant "CourseService" as SRV <<service>>
participant "Course" as C <<domain>>
participant "CourseMapper" as MAP <<mapper>>
participant "CourseDTO" as DTO <<dto>>

database CourseRepository as REP <<repository>>

activate M

M -> UI : asks to list all the courses and their states
activate UI

UI -> CTRL : new
activate CTRL
CTRL -> SRV : new(courseRepository)
deactivate CTRL

UI -> CTRL : listNotClosedCourses()
activate CTRL
CTRL -> SRV : listNotClosedCourses()
activate SRV
SRV -> REP : findAllNotClosed()
activate REP
REP --> SRV : courses
deactivate REP

loop for each course
  SRV -> MAP : toDTO(courses)
  activate MAP
  deactivate MAP
end loop

SRV --> CTRL : courses
deactivate SRV
CTRL --> UI : courses
deactivate CTRL

UI --> M : lists all the non finished courses
deactivate UI

M -> UI : selects the desired course
activate UI
UI -> UI : selectedCourse = get(index)
UI --> M : asks to confirm action
deactivate UI

M -> UI : confirms the action
activate UI
UI -> CTRL : toggleEnrolmentState(selectedCourse)
activate CTRL
CTRL -> SRV : toggleEnrolmentState(course)
activate SRV
SRV -> C : toggleEnrolmentState()
activate C
deactivate C
deactivate SRV
CTRL -> SRV : save(course)
activate SRV
SRV -> REP : save(selectedCourse)
activate REP
deactivate REP
SRV --> CTRL : newCourse
deactivate SRV
CTRL --> UI : newCourse
deactivate CTRL
UI--> M : reports the success of the toggle operation
deactivate UI

deactivate M

@enduml
