@startuml US1003_SSD
autonumber

actor "Manager" as M
participant "System" as SYS

activate M

M -> SYS : asks to list all the courses and their states
activate SYS
SYS --> M : lists all the non finished courses & current state
deactivate SYS

M -> SYS : selects the desired course
activate SYS
SYS --> M : asks to confirm action
deactivate SYS

M -> SYS : confirms action
activate SYS
SYS --> M : reports the success of the toggle operation
deactivate SYS

deactivate M

@enduml
