@startuml US2009_SSD
autonumber

actor Student as "Student"
actor System as "System"

activate Student
activate System

Student -> System : The Student requests to take an formative exam

System --> Student : The System asks to select a course

Student -> System : The Student selects a course

System --> Student : The System asks to select an exam

Student -> System : The Student selects an exam

System --> Student : The System presents the exam to the Student

Student -> System : The Student answers the questions and submits the exam

System --> Student : The System calculates the grade and feedback of the exam

deactivate System
deactivate Student

@enduml
