@startuml US1006_SSD
autonumber

actor "User" as U
participant "System" as SYS

activate U

U -> SYS : asks to list the available courses
activate SYS
SYS --> U : lists all available courses
deactivate SYS

deactivate U

@enduml
