@startuml US4001_SD
autonumber

actor "User" as U

participant "ScheduleMeetingUI" as UI <<presentation>>
participant "ScheduleMeetingController" as CTRL <<application>>
participant "UserManagementService" as UMS <<service>>
participant "Meeting" as MEETING <<domain>>
participant "MeetingService" as MS <<service>>
participant "ScheduleAvailabilityService" as SAS <<service>>

database MeetingRepository as MR <<repository>>
database InviteRepository as IR <<repository>>

activate U

U -> UI : Asks to schedule a meeting
activate UI

UI --> U : requests the data needed to schedule a meeting
deactivate UI

U -> UI : types the requested data
activate UI

UI -> CTRL : getUsers()
activate CTRL

CTRL -> UMS : allUsers()
activate UMS
deactivate UMS

deactivate CTRL

UI --> U : asks to select the users to invite
deactivate UI

U -> UI : selects the users to invite
activate UI

UI -> CTRL : checkIfUsersAreAvailable()
activate CTRL

CTRL -> SAS : areAllAvailable()
activate SAS
deactivate SAS
deactivate CTRL

UI --> U : informs if the data is valid and if all users can attend the meeting
deactivate UI

U -> UI : confirms the data
activate UI

UI -> CTRL : scheduleMeeting()
activate CTRL

CTRL -> MEETING : new()
activate MEETING
deactivate MEETING

CTRL -> MR : saveMeeting()
activate MR
deactivate MR

CTRL -> CTRL : sendInvites()
activate CTRL

CTRL -> IR : saveInvite()
activate IR
deactivate IR
deactivate CTRL

UI --> U : informs operation sucess
deactivate UI

deactivate U

@enduml
