@startuml US2003_CD

class ListCourseExamsUI {

}

class ListCourseExamsController {
- courseListService
- courseRepository
- authorizationService
- examListService
+ listOpenInProgressCourses()
+ listCourseExams(course)
}


class Course {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt
  + toDto()
}

class RepositoryFactory {
  + RepositoryFactory()
}

interface CourseRepository {
  + findAllOpen()
  + findAllInProgress()
}

interface EvaluationExamRepository {
+ findAllCourseExams(course)
}

interface FormativeExamRepository {
+ findAllCourseExams(course)
}

class EvaluationExamListService {
- examRepository
+ listAllCourseExams(course)
}

class FormativeExamListService {
- examRepository
+ listAllCourseExams(course)
}

class CourseListService {
  - courseRepository

  + listOpenCourses()
  + listInProgressCourses()
}


class EvaluationExamDTO {
- code
- title
- course
- teacher
- startTime
- endTime
- identifier
- description
- state
}

class EvaluationExam {
- code
- title
- course
- teacher
- startTime
- endTime
- identifier
- description
- state
+ toDto()
}

class FormativeExam {
- code
- title
- course
- teacher
- identifier
- description
- state
+ toDto()
}

class FormativeExamDTO {
- code
- title
- course
- teacher
- identifier
- description
- state
}

class CourseDTO {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt
}



class InMemoryCourseRepository {
  + findAllOpen()
  + findAllInProgress()
}

class JpaCourseRepository {
  + findAllOpen()
  + findAllInProgress()
}

class InMemoryFormativeExamRepository {
+ findAllCourseExams(course)
}

class JpaFormativeExamRepository {
+ findAllCourseExams(course)
}

class InMemoryEvaluationExamRepository {
+ findAllCourseExams(course)
}

class JpaEvaluationExamRepository {
+ findAllCourseExams(course)
}

class PersistenceContext {
  - repositories()
}


PersistenceContext ..> RepositoryFactory
RepositoryFactory --> CourseRepository
RepositoryFactory --> FormativeExamRepository
RepositoryFactory --> EvaluationExamRepository

CourseRepository <|.. InMemoryCourseRepository
CourseRepository <|.. JpaCourseRepository

EvaluationExamRepository <|.. InMemoryEvaluationExamRepository
EvaluationExamRepository <|.. JpaEvaluationExamRepository

FormativeExamRepository <|.. InMemoryFormativeExamRepository
FormativeExamRepository <|.. JpaFormativeExamRepository


ListCourseExamsController ..> PersistenceContext
ListCourseExamsUI ..> ListCourseExamsController


CourseListService ..> Course
CourseListService ..> CourseRepository

FormativeExamListService ..> FormativeExamDTO
FormativeExamListService ..> FormativeExam

EvaluationExamListService ..> EvaluationExamDTO
EvaluationExamListService ..> EvaluationExam

CourseListService ..> CourseDTO
ListCourseExamsController --> FormativeExamListService
ListCourseExamsController --> CourseListService
ListCourseExamsController --> EvaluationExamListService

EvaluationExamListService ..> EvaluationExamRepository
FormativeExamListService ..> FormativeExamRepository


@enduml
