@startuml US2003_CD

class ListCourseExamsUI {

}

class ListCourseExamsController {
- courseListService
- courseRepository
- authorizationService
- examListService
+ listOpenInProgressCourses()
+ listCourseExams(course)
}


class Course {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt
  + toDto()
}

class RepositoryFactory {
  + RepositoryFactory()
}

interface CourseRepository {
  + findAllOpen()
  + findAllInProgress()
}

class CourseListService {
  - courseRepository

  + listOpenCourses()
  + listInProgressCourses()
}

class ExamListService {
- examRepository
+ listAllCourseExams(course)

}

class Exam {
- code
- course
- teacher
- identifier
- title
- description
- state
+ toDto()
}

class ExamDTO {
- code
- course
- teacher
- identifier
- title
- description
- state
}

class CourseDTO {
  - code
  - title
  - description
  - enrolmentLimits
  - courseState
  - courseEnrolmentState
  - createdAt
}



class InMemoryCourseRepository {
  + findAllOpen()
  + findAllInProgress()
}

class JpaCourseRepository {
  + findAllOpen()
  + findAllInProgress()
}

class PersistenceContext {
  - repositories()
}


PersistenceContext ..> RepositoryFactory
RepositoryFactory --> CourseRepository

CourseRepository <|.. InMemoryCourseRepository
CourseRepository <|.. JpaCourseRepository
ListCourseExamsController ..> PersistenceContext
ListCourseExamsUI ..> ListCourseExamsController

ExamListService ..> Exam
CourseListService ..> Course
CourseListService ..> CourseRepository

ExamListService ..> ExamDTO
CourseListService ..> CourseDTO

ListCourseExamsController --> CourseListService
ListCourseExamsController --> ExamListService


@enduml
