@startuml US4003_STATE

[*] --> PENDING : create

PENDING --> ACCEPT : accept
PENDING --> REJECT : reject
PENDING --> NO_ANSWER : no answer
PENDING --> CANCELED : canceled

ACCEPT --> [*]
REJECT --> [*]
NO_ANSWER --> [*]
CANCELED --> [*]

@enduml
