@startuml DM_Auth

class AuthenticationService <<service>> {
  + authenticate()
}
class AuthorizationService <<service>> {}
class PasswordPolicy <<service>> {}

class SimplePasswordEncoder <<service>> {}
class PasswordHashEncoder <<service>> {}
interface PasswordEncoder {}
' class PasswordEncoderFactory {}

class UserSession {}

entity SystemUser <<(E,#8dc8f6) entity>> <<root>>

class Username <<(V,#FF8B40) value object>> <<id>> {}
class Password <<(V,#FF8B40) value object>> {}
class Role <<(V,#FF8B40) value object>> {}

AuthenticationService ..> AuthorizationService
AuthenticationService ..> Username
AuthenticationService ..> Password
AuthenticationService ..> Role
AuthenticationService ..> PasswordPolicy
AuthenticationService ..> PasswordEncoder

PasswordEncoder <|-- SimplePasswordEncoder
PasswordEncoder <|-- PasswordHashEncoder

Password ..> PasswordPolicy
Password ..> PasswordEncoder

AuthorizationService --> UserSession

UserSession --> SystemUser

SystemUser --> Username
SystemUser --> Password

@enduml
