@startuml US2004_SSD
autonumber

actor "Student" as student
participant ":System" as system

activate student

student -> system : Asks to take an exam

activate system

system -> student : Lists all courses that the current\nstudent is enrolled in and asks to select one
student -> system : Selects a course

system -> student : Lists all exams that are open for the\nselected course and asks to select one
student -> system : Selects an exam

loop for each question
  system -> student : Shows a question and asks to answer it
  student -> system : Answers the question
end loop

opt if feedback show option is enabled
  system -> student : Shows feedback
end opt
opt if grade show option is enabled
  system -> student : Shows grade
end opt

deactivate system
deactivate student

@enduml
