@startuml US4004_SD
autonumber

actor "User" as U

participant "ListMeetingUI" as UI <<presentation>>
participant "ListMeetingController" as CTRL <<controller>>
participant "MeetingService" as MS <<service>>

database MeetingRepository as MR <<repository>>
database InviteRepository as IR <<repository>>

activate U

U -> UI : asks to check list of meetings
activate UI

UI -> CTRL : getMeetingList()
activate CTRL

CTRL -> MS : notCanceledMeetingsSheduledBy()
activate MS

MS -> MR : findNotCanceledMeetingsByOwner()
activate MR
deactivate MR

deactivate MS

deactivate CTRL

UI --> U : shows list and asks to select meeting
deactivate UI

U -> UI : selects meeting
activate UI

UI -> CTRL : getMeetingDetails()
activate CTRL

CTRL -> MS : getAllInvitesByMeeting()
activate MS

MS -> IR : findByMeetingID()
activate IR
deactivate IR

deactivate MS

deactivate CTRL

UI --> U : shows list of participants and their status
deactivate UI

deactivate U

@enduml
