@startuml US4004_SSD
autonumber

actor User as "User"
actor System as "System"

activate User
activate System

User -> System : asks to check list of meetings

System --> User : shows list

User -> System : selects meeting

System --> User : shows list of participants and their status

deactivate System
deactivate User


@enduml
