@startuml DM
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> User" {
  entity User
}

entity User <<entity>> <<root>> {
  - isActive
}

package "<<aggregate>> Teacher" {
  entity Teacher
}

entity Teacher <<entity>> <<root>> {

}

package "<<aggregate>> Student" {
  entity Student
}

entity Student <<entity>> <<root>> {

}

package "<<aggregate>> Manager" {
  entity Manager
}

entity Manager <<entity>> <<root>> {

}

package "<<aggregate>> Course" {
  entity Course
}

entity Course <<entity>> <<root>> {
  - code
}

package "<<aggregate>> Board" {
  entity Board
}

entity Board <<entity>> <<root>> {
}

package "<<aggregate>> Enrolment" {
  entity Enrolment
}

entity Enrolment <<entity>> <<root>> {
}

package "<<aggregate>> PostIt" {
  entity PostIt
}

entity PostIt <<entity>> <<root>> {

}

package "<<aggregate>> Meeting" {
  entity Meeting
}

entity Meeting <<entity>> <<root>> {

}

package "<<aggregate>> Class" {
  entity Class
}

entity Class <<entity>> <<root>> {

}

package "<<aggregate>> Invite" {
  entity Invite
}

entity Invite <<entity>> <<root>> {

}

package "<<aggregate>> ExtraordinaryClass" {
  entity ExtraordinaryClass
}

entity ExtraordinaryClass <<entity>> <<root>> {

}

package "<<agregate>> ExamAnswer" {
  entity ExamAnswer
  entity AnswerToQuestion
}

package "<<agregate>> Question" {
  entity Question
}

entity Question <<entity>> <<root>> {}
entity ExamAnswer <<entity>> <<root>> {}
entity AnswerToQuestion <<entity>> {}


package "<<agregate>> Exam" {
  entity Exam
  entity Section
  entity SectionQuestion
}

entity Exam <<entity>> <<root>> {
  -date
}
entity Section <<entity>> {}
entity SectionQuestion <<entity>> {}

entity ExamAnswer <<entity>> <<root>> {

}

package "<<aggregate>> FormativeExam" {
  entity FormativeExam
}

entity FormativeExam <<entity>> <<root>> {
}

package "<<aggregate>> EvaluationExam" {
  entity EvaluationExam
}

entity EvaluationExam <<entity>> <<root>> {
}


Teacher -|> User
Student --|> User
Manager --|> User

Course ---> "1..*" Teacher : has
Course --> "1" Teacher : has a responsible

Enrolment --> "1" Course : is for
Enrolment --> "1" Student : has

Board ---> "1" User : has an owner

PostIt --> "1" Board: belongs to
PostIt --> "0..1" PostIt : previous

Exam ---> "1" Course : is from
Exam --> "1" Teacher : is created by
Exam *-- "1..*" Section
Exam <|- EvaluationExam
Exam <|-- FormativeExam

Section *-- "1..*" SectionQuestion
SectionQuestion --> "1" Question : corresponds to

ExamAnswer --> "1" Exam : is for
ExamAnswer *-- "1..*" AnswerToQuestion
AnswerToQuestion --> "1" Question : is for

Invite --> "1" User : invites
Invite --> "1" Meeting : is related to

Class ---> "1" Course : is related to
Class ---> "1" Teacher : scheduled by

ExtraordinaryClass --> "1" Teacher : scheduled by
ExtraordinaryClass --> "1..*" Student : has
ExtraordinaryClass --> "1" Course : is related to

Student --> "0..*" ExamAnswer : has

Meeting --> "1" User : scheduled by

Question --> "1" Course : has

@enduml
