@startuml DM
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> User" {
    entity User
}

entity User <<entity>> <<root>> {
    - isActive
}

package "<<aggregate>> Teacher" {
    entity Teacher
}


entity Teacher <<entity>> <<root>> {
  -id
}

package "<<aggregate>> Student" {
    entity Student
}

entity Student <<entity>> <<root>> {
  -id
}

package "<<aggregate>> Manager" {
    entity Manager
}

entity Manager <<entity>> <<root>> {
  -id
}

package "<<aggregate>> Course" {
    entity Course
}

entity Course <<entity>> <<root>> {
    - code
}

package "<<aggregate>> Board" {
    entity Board
}

entity Board <<entity>> <<root>> {
}

package "<<aggregate>> Exam" {
    entity Exam
    entity Section
    entity Question
}

entity Exam <<entity>> <<root>> {
}

package "<<aggregate>> PostIt" {
    entity PostIt
}

entity PostIt <<entity>> <<root>> {
    -id
}

package "<<aggregate>> Event" {
    entity Event
}

entity Event <<entity>> <<root>> {
    -id
}

package "<<aggregate>> Meetings" {
    entity Meetings
}

entity Meetings <<entity>> <<root>> {
    -id
}

package "<<aggregate>> Class" {
    entity Class
}

entity Class <<entity>> <<root>> {
    -id
}

package "<<aggregate>> Answer" {
    entity Answer
}

entity Answer <<entity>> <<root>> {
    -id
}

Teacher --|> "1" User 
Student --|> "1" User 
Manager --|> "1" User

Course -> "0..*" Student : has students enroled
Course ---> "1..*" Teacher : has teachers
Course --> "1" Teacher : has a responsible

Board --> "1" User : has an owner
PostIt --> "1" Board: belongs to

Exam --> "1..*" Student : is taken by
Exam -> "1" Course : is for
Exam --> "0..*" Answer : has

Class --|> "1" Event
Meetings --|> "1" Event

Section --* "1..*" Question : has

Exam --* "1..*" Section : has

Student --> "0..*" Event: participate
Student --> "0..*" Answer : has

@enduml
