@startuml DM-COURSE
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> Board" {
    entity Board

    class Title
    class Duration
    class Type
}

Board --> "1" Title : is identified by

entity Board <<entity>> <<root>> {
}

class Title <<(V,#FF8B40) value object>> {}

@enduml
