@startuml DM-COURSE
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> Board" {
    entity Board

    class Title
    entity Column
    entity Row
    entity BoardEvent
}

package "<<aggregate>> User" {
    entity User
}

entity User <<entity>> <<root>> {
}

Board --> "1" Title : is identified by
Board --* "*" Column : has a collection of
Board --* "*" Row : has a collection of

entity Board <<entity>> <<root>> {
}

entity Column <<entity>> {
  - id
}

entity BoardEvent <<entity>> {
  - id
}

Column --> "1" Title : is identified by

entity Row <<entity>> {
  - id
}

Row --> "1" Title : is identified by

class Title <<(V,#FF8B40) value object>> {}

Board -> "*" BoardEvent : produces
Board --> "1" User : is owned by

@enduml
