@startuml DM-COURSE
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> Course" {
    entity Course

    class Title
    class State
}

package "<<aggregate>> Enrolment" {
    entity Enrolment
}

entity Course <<entity>> <<root>> {
    - code
}

entity Enrolment <<entity>> <<root>> {
}

package "<<aggregate>> Exam" {
    entity Exam
}

entity Exam <<entity>> <<root>> {
  -id
}

note left of State : Open\nOngoing\nClosed

class Title <<(V,#FF8B40) value object>> {}
class State <<(V,#FF8B40) value object>> {}

Course --> "1" Title : is titled
Course --> "1" State : is in
Enrolment --> "1" Course : is for

Exam --> "1" Course : is for

@enduml
