@startuml DM-COURSE
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> Course" {
    entity Course

    class Title
    class EnrolmentState
    class CourseState
}

package "<<aggregate>> Enrolment" {
    entity Enrolment
}

entity Course <<entity>> <<root>> {
    - code
    - createdAt
}

entity Enrolment <<entity>> <<root>> {
}

package "<<aggregate>> Exam" {
    entity Exam
}

entity Exam <<entity>> <<root>> {
  -id
}

package "<<aggregate>> Teacher" {
    entity Teacher
}

entity Teacher <<entity>> <<root>> {
    -id
}

package "<<aggregate>> Class" {
    entity Class
}

entity Class <<entity>> <<root>> {
    -id
}

note left of EnrolmentState : Open\nClosed
note bottom of CourseState : Open\nClosed

class Title <<(V,#FF8B40) value object>> {}
class EnrolmentState <<(V,#FF8B40) value object>> {}
class CourseState <<(V,#FF8B40) value object>> {}

Course --> "1" Title : is titled
Course --> "1" EnrolmentState : is in
Course ---> "1..*" Teacher : has
Course --> "1" Teacher : has a responsible
Course --> "1" CourseState : is in

Enrolment --> "1" Course : is for

Exam --> "1" Course : is for

Class ---> "1" Course : is related to

@enduml
