@startuml DM-STUDENT
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> User" {
    entity User
}

entity User <<entity>> <<root>> {
  - isActive
}

package "<<aggregate>> Enrolment" {
  entity Enrolment
}

entity Enrolment <<entity>> <<root>> {
}

package "<<aggregate>> ExamAnswer" {
  entity ExamAnswer
}

entity ExamAnswer <<entity>> <<root>> {
}

package "<<aggregate>> Student" {
  entity Student

  class BirthDate
  class TaxPayerNumber
  class MecanographicNumber
}

entity Student <<entity>> <<root>> {
}

class BirthDate <<(V,#FF8B40) value object>> {}
class TaxPayerNumber <<(V,#FF8B40) value object>> {}
class MecanographicNumber <<(V,#FF8B40) value object>> {}

Student --> "1" BirthDate : characterized by
Student --> "1" TaxPayerNumber : characterized by
Student --> "1" MecanographicNumber : identified by

Student -|> User

Student --> "0..*" Enrolment : produces

Student --> "0..*" ExamAnswer : has

@enduml
