name: Deployment

on:
  schedule:
    - cron: "10 4 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "master"

jobs:
  deploymeny:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Run properties.sh
        run: ./properties.sh

      - name: Build with Maven
        run: mvn dependency:copy-dependencies package --file pom.xml

      - name: Copy Bootstrap
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "ecourse.app.bootstrap/app.bootstrap-1.0.0.jar,ecourse.app.bootstrap/target/dependency/*"
          target: "~/deploy/bootstrap"

      - name: Copy Shared Board Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "ecourse.daemon.board/target/daemon.board-1.0.0.jar,ecourse.daemon.board/target/dependency/*,deploy.sh"
          target: "~/deploy"

      - name: Deploy Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy
            killall java
            ./deploy.sh &
